### ISSUE TITLE
Version 1.1.0 requires Xcode 7.?+

### ISSUE THREAD

**Issue by maschall** [facebook/KVOController#104]
I'm not sure what the new minimum Xcode version required, but with the new changes in 1.1.0 Xcode 6.4 is no longer supported due to #91.

I'm not sure if there is a good way to call attention to it, but just in case it breaks anyone else's projects, they need to lock down the version

**Comment by nlutsenko** [comment]
Indeed, we require Xcode 7.0+ with the latest version, since generics and nullability specifiers.
Just mentioned this in the release notes right now, thanks for bringing this up.
