### ISSUE TITLE
Include prebuilt framework in releases

### ISSUE THREAD

**Issue by davbeck** [facebook/KVOController#111]
If a library includes a pre-built framework with their release in Github, Carthage will download that instead of building the framework every time. Additionally, some apps may want to just download the framework directly and include it in their project directly.

See https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file.

**Comment by nlutsenko** [comment]
Sure, I don't feel strongly about archiving/non-archiving it for releases.
The only downside is that we don't have a built-in script solution, but I can add one, say via Makefile.

**Comment by nlutsenko** [comment]
@davbeck, just compiled one for latest release - 1.1.0, which is the earliest supported version that we have. Going to add a Makefile that can do this right now.

**Comment by davbeck** [comment]
One thing I forgot to mention, this should only be done for frameworks that don't use Swift until the ABI is stabilized, so if KVOController ever adds any Swift files, we need to pull support for this. Apps written in Swift and linking to ObjC libraries like KVOController can still take advantage of the feature though.
