### ISSUE TITLE
compile error with cocoapods 1.0.1

### ISSUE THREAD

**Issue by shiyizju** [facebook/KVOController#115]
encounter compile error - "KVOController/FBKVOController.h" file not found - with cocoapods 1.0.1, when add 'use_frameworks!' in podfile.
<img width="655" alt="screen shot 2016-09-05 at 11 35 26 pm" src="https://cloud.githubusercontent.com/assets/1643516/18252559/a902d034-73c1-11e6-8927-72f0a4a19d0b.png">

**Comment by nlutsenko** [comment]
Hey @shiyizju, thanks for the report.
Unfortunately, I can't reproduce the problem in any way.
Here is the test project I used:
[KVOTest.zip](https://github.com/facebook/KVOController/files/455580/KVOTest.zip)

If you could provide the full log or a repro project or more steps to reproduce the problem, so we can fix it for you - that would be super helpful. Please reopen with more details.
