### ISSUE TITLE
retain cycle!

### ISSUE THREAD

**Issue by wpstarnice** [facebook/KVOController#122]
Question description:1 self is observer, 
                                    2 self is observed,
                                    3 name is one property of self

Try 1:retain cycle
 {
    FBKVOController *_fbKVO;
}
.............................................
    FBKVOController *fb = [FBKVOController controllerWithObserver:self];
    _fbKVO = fb;
    [_fbKVO observe:self keyPath:NSStringFromSelector(@selector(name)) options:NSKeyValueObservingOptionOld|NSKeyValueObservingOptionNew block:^(id _Nullable observer,id object, NSDictionary<NSString *, id> *change) {
        **[observer doSomething];** or **[object doSomething];**
    }];

Try 2:retain cycle
    [self.KVOControllerNonRetaining observe:self keyPath:NSStringFromSelector(@selector(name)) options:NSKeyValueObservingOptionOld|NSKeyValueObservingOptionNew block:^(id _Nullable observer,id object, NSDictionary<NSString *, id> *change) {
        **[observer doSomething];** or **[object doSomething];**
    }];

Try 3:retain cycle again

 [self.KVOControllerNonRetaining observe:self keyPath:NSStringFromSelector(@selector(name)) options:NSKeyValueObservingOptionOld|NSKeyValueObservingOptionNew block:^(id _Nullable observer,id object, NSDictionary<NSString *, id> *change) {
        **[observer doSomething];** or **[object doSomething];**
    }];

-(void)dealloc
{
    [self.KVOControllerNonRetaining unObserveAll];
}
any other way to solve it ? thanks

**Comment by wpstarnice** [comment]
@nlutsenko

**Comment by wpstarnice** [comment]
anyone help?...

**Comment by marcuswu0814** [comment]
@wpstarnice 

See `KVOController.m` file and these two methods:

~~~objc
#pragma mark Lifecycle -

+ (instancetype)controllerWithObserver:(nullable id)observer
{
  return [[self alloc] initWithObserver:observer];
}

- (instancetype)initWithObserver:(nullable id)observer
{
  return [self initWithObserver:observer retainObserved:YES];
}
~~~
By default, the factory method `controllerWithObserver:` retain observed.

You own a KVOController instance, and KVOController retain yourself, it cause to retain cycle.

If you really want to do something with this, using `initWithObserver:observer:retainObserved:`, and pass the argument `NO` to create a instance that didn't retain yourself.

By the way, maybe you can override your `name` property's setter, and do something with hook, right?

**Comment by nlutsenko** [comment]
@wpstarnice, sorry, took a long while to reply.

@marcuswu0814 is absolutely correct, by default the KVOController is going to retain the observed objects. Specifically for this - there is an additional constructor [`-initWithObserver:retainObserved:`](https://github.com/facebook/KVOController/blob/master/FBKVOController/FBKVOController.h#L79) as well as an additional category property [`KVOControllerNotRetaining`](https://github.com/facebook/KVOController/blob/master/FBKVOController/NSObject%2BFBKVOController.h#L38) inside [NSObject+FBKVOController](https://github.com/facebook/KVOController/blob/master/FBKVOController/NSObject%2BFBKVOController.h#L38).

Let us know if you have any more questions.
