### ISSUE TITLE
Dispatch notifications on a given queue?

### ISSUE THREAD

**Issue by zoul** [facebook/KVOController#18]
Would it be possible to dispatch the notification block on a given queue? One of my most frequent use cases is propagating changes from model code running in background threads back to the UI. That means the notifications fire on the background thread and I have to `dispatch_async` onto the main queue manually all the time. It would be nice to have a feature in `KVOController` to set the “target” notification queue.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
