### ISSUE TITLE
Why not allow duplication observation?

### ISSUE THREAD

**Issue by onmyway133** [facebook/KVOController#24]
Hi, your API does not allow duplication

"Observing nil or observing an already observed object's key path results in no operation"

Why is that? What if people want to observer that same object, same keypath 2 times ?

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
