### ISSUE TITLE
Selector only executed for .Initial but never again.

### ISSUE THREAD

**Issue by Sajjon** [facebook/KVOController#45]
Hi, I am testing to use this project in Swift. In the code below I have an UITextField hooked up as an outlet. I marked the outlet as "dynamic", as suggested here: http://stackoverflow.com/a/25219216, at least that what I think I am suppose to do.

Anyway, when I run the code it prints "New email: test@test.test" since I am setting the text to that (before setting up the KVO), this works since the option .Initial is chosen.

But when I change the text in the UITextField nothing happens. What am I doing wrong?

Is it possible to use this with UITextFields in Swift?

Thanks for any help!

```swift
   @IBOutlet weak dynamic var emailField: UITextField!

    override func viewDidLoad() {
        super.viewDidLoad()
        emailField.text = "test@test.test"
        setupKVO()
    }

    func setupKVO() {
        let options : NSKeyValueObservingOptions = .New | .Old | .Initial | .Prior
        self.KVOController.observe(self.emailField, keyPath:"text", options: options, action:"newEmail:")
    }
    
    func newEmail(change: NSDictionary) {
        if let newEmail: String = change["new"] as? String {
            println("New email: \(newEmail)")
        }
    }
```

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
