### ISSUE TITLE
KVO self with self observer

### ISSUE THREAD

**Issue by RuiAAPeres** [facebook/KVOController#48]
A bit of context first: I am using MVVM and I have a VC with a VM. The VC is observing one property of the VM. Now is the thing: I want the VM to observe himself for two keyPaths and once there is a change, if it's passes a validation, I will update the property the VC is observing. On the VM I would have something like:

```
[self.KVOController observe: self keyPaths:@[keyPath1,keyPath2] options:NSKeyValueObservingOptionInitial | NSKeyValueObservingOptionNew block:^(ViewModel *observer, ViewModel *observed, NSDictionary *change) {

}];
```
So my two problems:

1. The VM get's retained and it's never released (dealloc is not called). I would like it to behave as expected: lifetime tied with its VC. 
2. Is this pattern fundamentally wrong?

The goal here is to avoid exposing the two inner properties to VC (I don't think he should be exposed to those)

**Comment by Nikita2k** [comment]
Hi, @RuiAAPeres !

I've met the exact same problem with observing self. Here is what I found so far:
1. You can use `initWithObserver:retainObserved:` and do NOT retain observer.
2. Then you should call `unobserveAll` before object's `dealloc` (for UIViewController you can call in disappearing methods).

The reason it happens is NSMapTable (which is used in FBKVOController) releases keys before objects actually deallocs and doesn't unsubscribe properly from KVO.

You can also use custom setters and call observing method manually (I believe that it's a hack).

I'm going to propose a pull request in a day or two, so you don't need this hack.

**Comment by RuiAAPeres** [comment]
Hi @Nikita2k 

The issue I have is the 2. one. I am using this on a ViewModel (NSObject's subclass). I would prefer to use the `unobserveAll` on dealloc, but I am aware it won't work (I tried and memory leak is there).

**Comment by Nikita2k** [comment]
@RuiAAPeres as far as I understand you can't use `unobserveAll` in dealloc because of described behaviour of NSMapTable.

**Comment by RuiAAPeres** [comment]
@Nikita2k I need to spend some time and check how RAC is able to solve that issue.

**Comment by nonamelive** [comment]
I'm having the exact same problem with FBKVOController. I'm still looking for a solution, but as for now, I have to remove all code like this to avoid retain cycles.

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by joerick** [comment]
I'm also having this problem. I've fallen back to using the Cocoa KVO API for this one case in my app. With the Cocoa KVO API you can call removeObserver:forKeyPath: in -dealloc.

**Comment by lxcid** [comment]
Just to note that I am having similar issue as well.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by nonamelive** [comment]
Can anyone confirm #67 fixes this issue?

**Comment by Nikita2k** [comment]
@nonamelive in my case everything works perfectly

**Comment by hzwzw** [comment]
@nonamelive @Nikita2k 
Thank you all guys!
I'm sure it works very well.
I will add some tests later.

**Comment by Whirlwind** [comment]
Why close this issue? The pull request is not be merged.

**Comment by nonamelive** [comment]
Vote for reopen.

**Comment by Whirlwind** [comment]
@kimon Why did you close so many issues with same comments?

**Comment by grp** [comment]
Hi, so there isn't a safe way to implement this. If you are observing self, then self cannot define the lifetime of the observation because that would create a retain cycle. So you have to maintain the lifecycle manually, and make sure the observation is removed before `dealloc`.

You can often override the setter rather than KVO self, which is simpler in all cases.

**Comment by Whirlwind** [comment]
@grp 

The PR #67 can fix it.

```
You can often override the setter rather than KVO self, which is simpler in all cases.
```

You are right, but I often KVO a property of the controller's parent controller, it also cause a retain cycle. Will you fix it?
