### ISSUE TITLE
Road to v1.0.4

### ISSUE THREAD

**Issue by Ashton-W** [facebook/KVOController#50]
There have been some minor changes since v1.0.3 that aren't released on CocoaPods - or in a tagged release. Is there a roadmap for what has to be done before the next release, or did someone just have to ask ;)

We could perhaps use the 'Milestones' feature in GitHub.

:heart: KVOController

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
