### ISSUE TITLE
No access to keyPath inside block of - observe:keyPaths:options:block:

### ISSUE THREAD

**Issue by SamWyndham** [facebook/KVOController#51]
In the following method (which accepts multiple keyPaths) it would be nice to know, within the block, the keyPath of the value that has changed:

- observe:keyPaths:options:block:

**Comment by BarneyBear** [comment]
I've added a keyPath argument to the block and updated the tests in our fork: https://github.com/interaktionsbyran/KVOController, I'm considering a pull request, but I have changed the API so I'm not sure if it'll be accepted.

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by tettoffensive** [comment]
@kimon did this get merged? and if so is it in a stable version? I'm using this in production and right now don't seem to have access to the keyPath with `- (void)observe:(id)object keyPaths:(NSArray *)keyPaths options:(NSKeyValueObservingOptions)options block:(FBKVONotificationBlock)block;`

**Comment by modocache** [comment]
@BarneyBear the [changes in your fork](https://github.com/facebook/KVOController/compare/master...interaktionsbyran:keyPath) look good!

> I'm considering a pull request, but I have changed the API so I'm not sure if it'll be accepted.

Is it possible to make the change without breaking the existing API? Perhaps by defining a new block separate from `FBKVONotificationBlock`, and a new method that delivers callbacks using the new block?

> did this get merged? and if so is it in a stable version?

@tettoffensive It is not! Feel free to use @BarneyBear's fork, or send a pull request to this repository. Sorry for the inconvenience! :bow:

**Comment by BarneyBear** [comment]
@modocache I'll have a look when I get in to the office and see if I can perserve the API to avoid breaking existing code. If so I can submit a pull request.

**Comment by modocache** [comment]
@BarneyBear Awesome, thanks! :bouquet:

**Comment by BarneyBear** [comment]
So... me coding c++ for the last 6 months has apparently scrambled my brain. Objective-C does obviously not consider message parameter types for signature generation. What would be the preferred way of introducing the new block. A message with keyPathBlock instead of just block?

**Comment by tettoffensive** [comment]
@BarneyBear I started to create a fork myself and try to not break the API. but I was thinking of making a separate block. But there's not really a clean way to do it that I could think of. Checking a block signature in objective c isn't a straightforward thing. For now, I'm just converting my project to use the new block everywhere
