### ISSUE TITLE
README Example of KVO with and without KVOController

### ISSUE THREAD

**Issue by Ashton-W** [facebook/KVOController#53]
It would be great to include an example in the README (or a link to a wiki page) that shows the benefits of **KVOController** by example.
Show code using **KVOController**, then the equivalent correct and safe usage of plain KVO.

The example code could be a `UIViewController` subclass, I think that is a common usage.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tarzon** [comment]
I am also interested in this.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
