### ISSUE TITLE
NSObject Category not included in pod

### ISSUE THREAD

**Issue by tal** [facebook/KVOController#54]
I just installed the latest pod and xcode cannot find `#import <KVOController/NSObject+FBKVOController.h>`

When investigating i saw that the file doesn't appear to be included
[![](http://tal.by/5P.png)](http://tal.by/5P.png)

*Edit* just realized it's probably related to #50

**Comment by studentdeng** [comment]
same here. Anyone help?

**Comment by grp** [comment]
You can probably use a commit hash rather than a specific version for commits that aren't in the Cocoapods repo yet.

**Comment by koszcz** [comment]
Category is in the FBKVOController.h. Not in a separate file.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
