### ISSUE TITLE
KVOController for NSNotificationCenter

### ISSUE THREAD

**Issue by pronebird** [facebook/KVOController#55]
I think it would be a great addition to library. I guess both KVO and NC are similar so it shouldn't be a big deal to extend existing functionality.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by pronebird** [comment]
Bump?

**Comment by grp** [comment]
What kind of features would be useful for a KVOController-style observer of NSNotificationCenter? That class already supports blocks, and in iOS 9, automatic deobservation.

**Comment by pronebird** [comment]
@grp didn't know about automatic deobservation on iOS 9.0. Closing then.
