### ISSUE TITLE
Cannot remove observer from inside the observing block

### ISSUE THREAD

**Issue by koszcz** [facebook/KVOController#57]
When i want to remove observation outside the observation block:
```
self.simpleObject = [SimpleObject new];
[self.KVOController observe:self.simpleObject
                    keyPath:NSStringFromSelector(@selector(simpleProperty))
                    options:NSKeyValueObservingOptionInitial|NSKeyValueObservingOptionNew
                      block:^(AppDelegate *observer, id object, NSDictionary *change) {
                          
}];
    
[self.KVOController unobserve:self.simpleObject];
```
then everything is fine, but when i want to remove observer from inside the block
```
self.simpleObject = [SimpleObject new];
[self.KVOController observe:self.simpleObject
                    keyPath:NSStringFromSelector(@selector(simpleProperty))
                    options:NSKeyValueObservingOptionInitial|NSKeyValueObservingOptionNew
                      block:^(AppDelegate *observer, id object, NSDictionary *change) {
                            [observer.KVOController unobserve:observer.simpleObject];
}];
```

then i got crash, is it done by design or is it a bug?

```
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <_FBKVOSharedController 0x7fa62a62d350> for the key path "simpleProperty" from <SimpleObject 0x7fa62a62b890> because it is not registered as an observer.
```

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kimon** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by siyusong** [comment]
I can confirm that I am still experiencing this problem when using 1.0.3. Can we reopen this issue?

**Comment by wizzardchao** [comment]
Hi @siyusong, even the native KVO system will call the block simultaneously before the registration of KVO if you specify option NSKeyValueObservingOptionInitial. At that time, the registration is not completed.
So I think it's not a bug of FBKVOController, you can just remove the Initial option as it's a limitation of KVO.

**Comment by siyusong** [comment]
Hi @wizzardchao,

Thanks for the explanation. I checked Apple's documentation of [NSKeyValueObservingOptionInitial](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Protocols/NSKeyValueObserving_Protocol/index.html#//apple_ref/c/econst/NSKeyValueObservingOptionInitial), and it indeed mentioned the fact that observer registration may not be completed in that case:

> - NSKeyValueObservingOptionInitial

> If specified, a notification should be sent to the observer immediately, before the observer registration method even returns.

However, I disagree with you that this is not a bug of KVOController. The OP of this issue and I are using `- unobserve:` in KVOController, not `- removeObserver:forKeyPath:` method in Foundation. The discussion section of `- unobserve:` clearly mentions that, if the object is not observed, "this method results in no operation".

Therefore, I think it's reasonable for me to expect that `- unobserve:` method (and its siblings) would never result in an error.
