### ISSUE TITLE
Discussion: Switch filename to KVOController.h

### ISSUE THREAD

**Issue by orta** [facebook/KVOController#62]
I've started looking at using KVOController in a framework. Given that the Pod name is KVOController apple's framework expects either an umbrella header of the same name or the class having the same name. 

Both are options, but renaming to KVOController feels more like the intent of the library than adding an umbrella header.

**Comment by grp** [comment]
When you say "apple's framework expects", do you mean Xcode's header searching? Or `@import`?

**Comment by orta** [comment]
Just did some looking into it, looks like CocoaPods deals with all this under the hood, I just _presumed_, which is wrong. 

It generates an umbrella header, adding the right files:
```
#import <UIKit/UIKit.h>

#import "FBKVOController.h"

FOUNDATION_EXPORT double KVOControllerVersionNumber;
FOUNDATION_EXPORT const unsigned char KVOControllerVersionString[];
```

Closing, due to not really needing any action IMO.

**Comment by grp** [comment]
Cool, glad it worked!
