### ISSUE TITLE
Does this version support registering Dependent Keys?

### ISSUE THREAD

**Issue by hzwzw** [facebook/KVOController#66]
Like in [Apple Document](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/KeyValueObserving/Articles/KVODependentKeys.html#//apple_ref/doc/uid/20002179-SW5) says.
There is another example in my project, When users ended up editing his address information which contains many properties(eg: city, country, state, zip code ...), we need to know if any property has been changed and give user a alert about saving these changes. I want to add a "isModified" property to "address" model, and this property depends on other properties.
Thank a lot!

**Comment by hzwzw** [comment]
I just tested it, just like Apple says, use keyPathsForValuesAffecting<Key> method directly, FBKVOController supports registering Dependent Keys very well!
Thanks!

**Comment by grp** [comment]
Cool, anything that works with the standard KVO should work with KVOController too. Glad it does!
