### ISSUE TITLE
watchOS 2 

### ISSUE THREAD

**Issue by iclems** [facebook/KVOController#76]
Add to Podspec

**Comment by grp** [comment]
I'm not sure what this means — could you clarify?

**Comment by iclems** [comment]
Sorry, actually it's just about adding ```spec.watchos.deployment_target = '2.0'  ``` to the pod spec. Then it's compatible with watchOS 2

**Comment by grp** [comment]
We haven't tested KVOController on watchOS, but if it's working for you feel free to send a pull request! I'll add it if we use KVOController internally on watchOS and confirm it works fine.
