### ISSUE TITLE
Thread safety issue of rdar://15985376 seems unfixed

### ISSUE THREAD

**Issue by openaphid** [facebook/KVOController#83]
I'm trying to figure out how KVOController fixes [rdar://15985376](http://openradar.appspot.com/radar?id=5305010728468480). The code migrated  from radar project still crashes with the latest version of KVOController.

```Objective-C
- (void)testThreadCrash {
    FBKVOTestCircle * circle = [FBKVOTestCircle circle];
    
    FBKVOTestObserver * __block circleObserver = nil;
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
        while (YES) {
            circle.radius = CACurrentMediaTime(); //EXC_BAD_ACCESS on CFDictionaryGetValue
        }
    });
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
        while (YES) {
            @autoreleasepool {
                circleObserver = [FBKVOTestObserver observer];
                [circleObserver.KVOController observe:circle keyPath:@"radius" options:optionsBasic block:^(id observer, id object, NSDictionary *change) {
                    
                }];
            }
        }
    });
    
    [NSThread sleepForTimeInterval:3];
}

```

**Comment by grp** [comment]
I don't believe this is expected to be worked around in KVOController, since it's a crash inside KVO itself. Instead, I'd suggest trying to observe objects from the same thread or queue that changes their properties.

**Comment by openaphid** [comment]
Thanks, I think I misunderstood the document on thread-safety of KVOController.

**Comment by grp** [comment]
Yeah, I think it's best explained that KVOController tries to be thread safe with regards to deallocation of the observing object, rather than the observed object. The latter doesn't seem possible with KVO, sadly.
